<?php
namespace app\modules\user\models;
use Yii;
use yii\web\UploadedFile;
use yii\helpers\Html;

class UserInfo extends \yii\db\ActiveRecord
{

    public $province_area_id = 0;//省
    public $city_area_id = 0;//市
    public $county_area_id = 0;//区
    public $town_area_id = 0;//镇

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->setProvinceCityCounty($this->location);
    }

    private function setProvinceCityCounty($area_id)
    {
        $Area = new District();
        $area_info = $Area::findOne($area_id);

        if($area_info){
            switch($area_info->level){
                case 1:
                    $this->province_area_id = $area_info->id;
                    break;
                case 2:
                    $this->province_area_id = $area_info->pid;
                    $this->city_area_id = $area_info->id;
                    break;
                case 3:
                    $this->province_area_id = $Area::getParentId($area_info->pid);
                    $this->city_area_id = $area_info->pid;
                    $this->county_area_id = $area_info->id;
                    break;
                case 4:
                    $this->province_area_id = $Area::getPParentId($area_info->pid);
                    $this->city_area_id = $Area::getParentId($area_info->pid);
                    $this->county_area_id = $area_info->pid;
                    $this->town_area_id = $area_info->id;
                    break;
            }
        }
    }

    public static function tableName()
    {
        return '{{%user_info}}';
    }

    //获取当前用户名
    public static function nickName(){
        $user_info = UserInfo::findOne(['uid' => User::getUser()->id]);
        return $user_info->nickname;
    }
}